// Code generated by raiden-cli; DO NOT EDIT.
package bootstrap

import (
	"github.com/sev-2/raiden/pkg/resource"
	"mediversepreip/internal/roles"
)

func RegisterRoles() {
	resource.RegisterRole(
		&roles.SuperAdmin{},
	)
}
