PROJECT_NAME: aladinmall-batch-31
PROJECT_ID: knjskzzprajgyprjyrnk
DEPLOYMENT_TARGET: cloud

ACCESS_TOKEN:
ANON_KEY:
SERVICE_KEY:

SUPABASE_API_URL: https://api.supabase.com
SUPABASE_API_BASE_PATH: 
SUPABASE_PUBLIC_URL: https://knjskzzprajgyprjyrnk.supabase.co

SERVER_HOST: 127.0.01
SERVER_PORT: 8002

ENVIRONMENT: development
VERSION: 1.0.0

BREAKER_ENABLE: true

TRACE_ENABLE: false
TRACE_COLLECTOR: 
TRACE_COLLECTOR_ENDPOINT: 

CORS_ALLOWED_ORIGINS:
CORS_ALLOWED_METHODS:
CORS_ALLOWED_HEADERS:
